#!/bin/bash

# Define color codes for logging
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Log helper functions
log() { echo -e "$*" >&2; }
warn() { echo -e "${YELLOW}WARN:${NC} $*" >&2; }
error() { echo -e "${RED}ERROR:${NC} $*" >&2; }
info() { echo -e "$*" >&2; }

# Clear the screen for a clean setup experience
clear

# Ensure the script is running as root
if [ "$(id -u)" -ne 0 ]; then
    error "This script must be run as root. Please use sudo or run as root."
    sleep 5
    exit 1
fi

validate_user() {
    RET=0
    MSG="Entered username is invalid:"
    if [ -z "$USERNAME" ] || [ ${#USERNAME} -gt 32 ]; then
        MSG="$MSG\nLength be between 1 and 32 characters."
        RET=1
    fi
    if ! echo "$USERNAME" | grep -q '^[a-z]\{1\}[a-z0-9\-]*$'; then
        MSG="$MSG\nMust only contain lower-case letters, digits and hyphens, and must start with a letter."
        RET=1
    fi
    if [ "$USERNAME" = "root" ] || [ "$USERNAME" = "homebridge" ]; then
        MSG="$MSG\nCannot be root or homebridge."
        RET=1
    fi
    if [ "$RET" -ne 0 ]; then
        echo "$MSG"
    fi
    return "$RET"
}

validate_password() {
    PASSWORD="$1"
    MSG=""
    if [ -z "$PASSWORD" ]; then
        echo "Password cannot be empty."
        return 1
    fi
    if [ ${#PASSWORD} -le 5 ] || [ ${#PASSWORD} -gt 32 ]; then
        echo "Length be between 6 and 32 characters."
        return 1
    fi
}

display_message() {
    whiptail --title "Homebridge VM Image Setup" --msgbox "$1" 20 60
}

# Function to prompt for username with retry logic using whiptail
prompt_username() {
    local retries=3
    local attempt=1
    while [ $attempt -le $retries ]; do
        USERNAME=$(whiptail --title "Homebridge VM Image Setup" --inputbox "Enter the username for the new account:" 10 60 3>&1 1>&2 2>&3)
        exitstatus=$?
        if [ $exitstatus -ne 0 ]; then
            error "User canceled the setup. Exiting."
            sleep 30
            exit 1
        fi

        if MSG=$(validate_user); then
            return 0
        else
            whiptail --msgbox "$MSG" 20 60
        fi
        ((attempt++))
    done
    error "Maximum retries reached. Exiting."
    sleep 5
    exit 1
}

# Function to prompt for password with retry logic using whiptail
prompt_password() {
    local retries=3
    local attempt=1
    while [ $attempt -le $retries ]; do
        PASSWORD=$(whiptail --title "Homebridge VM Image Setup" --passwordbox "Enter password for $USERNAME:" 10 60 3>&1 1>&2 2>&3)
        exitstatus=$?
        if [ $exitstatus -ne 0 ]; then
            error "User canceled the setup. Exiting."
            sleep 5
            exit 1
        fi

        PASSWORD_CONFIRM=$(whiptail --title "Homebridge VM Image Setup" --passwordbox "Confirm password for $USERNAME:" 10 60 3>&1 1>&2 2>&3)
        exitstatus=$?
        if [ $exitstatus -ne 0 ]; then
            error "User canceled the setup. Exiting."
            sleep 5
            exit 1
        fi

        # Validate password using validate_password
        if [ "$PASSWORD" != "$PASSWORD_CONFIRM" ]; then
            whiptail --msgbox "Passwords do not match.\nPlease try again." 10 60
        elif validate_password "$PASSWORD"; then
            return 0
        else
            whiptail --msgbox "Invalid password: $(validate_password "$PASSWORD" 2>&1)\nPlease try again." 10 60
        fi
        ((attempt++))
    done
    error "Maximum retries reached. Exiting."
    sleep 5
    exit 1
}

display_message "Welcome to the Homebridge VM Image Setup!\n\nThis setup will guide you through creating a new user account for your Homebridge VM."
prompt_username
prompt_password

useradd -m -s /bin/bash -G sudo "$USERNAME"
echo "$USERNAME:$PASSWORD" | chpasswd


# Check if user creation was successful
if [ $? -eq 0 ]; then
    display_message "User '$USERNAME' created successfully!\n\nYou can now log in with this username and the password you provided."
else
    display_message "Failed to create user '$USERNAME'. Please check the system logs for more details."
    exit 1
fi

/usr/local/sbin/expandVirtualFilesystem

systemctl disable first-boot-homebridge
systemctl daemon-reload