#!/bin/sh

INTERACTIVE=True
ASK_TO_REBOOT=0
CONFIG=/boot/config.txt

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\e[1m'
NC='\033[0m'

is_live() {
    grep -q "boot=live" $CMDLINE
    return $?
}

is_ssh() {
  if pstree -p | egrep --quiet --extended-regexp ".*sshd.*\($$\)"; then
    return 0
  else
    return 1
  fi
}

is_fkms() {
  if grep -q okay /proc/device-tree/soc/v3d@7ec00000/status 2> /dev/null || grep -q okay /proc/device-tree/soc/firmwarekms@7e600000/status 2> /dev/null ; then
    return 0
  else
    return 1
  fi
}

is_installed() {
    if [ "$(dpkg -l "$1" 2> /dev/null | tail -n 1 | cut -d ' ' -f 1)" != "ii" ]; then
      return 1
    else
      return 0
    fi
}

deb_ver () {
  ver=`cat /etc/debian_version | cut -d . -f 1`
  echo $ver
}

calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
  # output from tput. However in this case, tput detects neither stdout or
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=17
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=80
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=120
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

set_config_var() {
  lua - "$1" "$2" "$3" <<EOF > "$3.bak"
local key=assert(arg[1])
local value=assert(arg[2])
local fn=assert(arg[3])
local file=assert(io.open(fn))
local made_change=false
for line in file:lines() do
  if line:match("^#?%s*"..key.."=.*$") then
    line=key.."="..value
    made_change=true
  end
  print(line)
end
if not made_change then
  print(key.."="..value)
end
EOF
mv "$3.bak" "$3"
}

get_web_addresses() {
  IP=$(hostname -I)

  printf "  ${BOLD}*${NC} ${GREEN}$1://$(hostname).local:$2$3${NC}\n"

  for ip in $IP; do
    if expr "$ip" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
      printf "  ${BOLD}*${NC} ${GREEN}$1://$ip:$2$3${NC}\n"
    else
      printf "  ${BOLD}*${NC} ${GREEN}$1://[$ip]:$2$3${NC}\n"
    fi
  done
}

get_ip_and_port() {
  IP=$(hostname -I)

  printf "  ${BOLD}*${NC} ${GREEN}$(hostname).local:$1$2${NC}\n"

  for ip in $IP; do
    if expr "$ip" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
      printf "  ${BOLD}*${NC} ${GREEN}$ip:$1$2${NC}\n"
    else
      printf "  ${BOLD}*${NC} ${GREEN}[$ip]:$1$2${NC}\n"
    fi
  done
}

do_finish() {
  if [ $ASK_TO_REBOOT -eq 1 ]; then
    whiptail --yesno "Would you like to reboot now?" 20 60 2
    if [ $? -eq 0 ]; then # yes
      sync
      reboot
    fi
  fi
  exit 0
}

get_first_user() {
  printf "$(getent passwd 1000 | cut -d: -f1)"
}

do_homebridge_update() {
  pstree -s $$ | grep "hb-service" > /dev/null
  if [ "$?" -eq 0 ]; then
    whiptail --title "Error" --msgbox "You cannot run this command from the Homebridge UI Terminal.\n\nPlease connect using SSH (see wiki for instructions) and try again." 20 60 1
    printf "\n"
    return
  fi

  curl -sfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null
  echo "deb [signed-by=/usr/share/keyrings/homebridge.gpg] https://repo.homebridge.io stable main" | sudo tee /etc/apt/sources.list.d/homebridge.list > /dev/null
  apt-get update --allow-releaseinfo-change
  apt-get install -y homebridge
}

do_restore_config() {
  pstree -s $$ | grep "hb-service" > /dev/null
  if [ "$?" -eq 0 ]; then
    whiptail --title "Error" --msgbox "You cannot run this command from the Homebridge UI Terminal.\n\nPlease connect using SSH (see wiki for instructions) and try again." 20 60 1
    printf "\n"
    return
  fi

  whiptail --yesno "This will remove all custom Homebridge config, plugins and restore to the factory default. You will need to manually remove any existing connections to this instance in the iOS Home app.\n\nAre you sure you want to proceed?" 20 60 2
  RET=$?
  if [ $RET -eq 0 ]; then
    apt-get purge -y homebridge
    do_homebridge_update
  fi
}

do_nodejs_update() {
  hb-service update-node
  exit 0
}




# use the utiltiy /usr/local/sbin/expandVirtualFilesystem

do_expand_filesystem() {
  whiptail --title "Warning" --yesno "This will expand the filesystem to use all available space on the virtual disk.\n\nThis operation may take several minutes to complete depending on the size of your virtual disk.\n\nAre you sure you want to continue?" 20 60 1
  RET=$?
  if [ $RET -eq 0 ]; then
    /usr/local/sbin/expandVirtualFilesystem
    RET=$?
    if [ $RET -eq 0 ]; then 
      whiptail --title "Success" --msgbox "The filesystem has been expanded successfully.\n\nYou need to reboot for the changes to take effect.\n\nIf needed the output is here - /var/log/diskexpand.log" 20 60 1
      ASK_TO_REBOOT=1
    else
      whiptail --title "Error" --msgbox "An error occured while attempting to expand the filesystem. Pls see output here - /var/log/diskexpand.log" 20 60 1
    fi
  fi
}

get_hostname() {
  tr -d " \t\n\r" < /etc/hostname
}   
  
do_hostname() {
  if [ "$INTERACTIVE" = True ]; then
    whiptail --msgbox "\
Please note: RFCs mandate that a hostname's labels \
may contain only the ASCII letters 'a' through 'z' (case-insensitive),
the digits '0' through '9', and the hyphen.
Hostname labels cannot begin or end with a hyphen.
No other symbols, punctuation characters, or blank spaces are permitted.\
" 20 70 1
  fi
  CURRENT_HOSTNAME=$(get_hostname)
  if [ "$INTERACTIVE" = True ]; then
    NEW_HOSTNAME=$(whiptail --inputbox "Please enter a hostname" 20 60 "$CURRENT_HOSTNAME" 3>&1 1>&2 2>&3) 
  else
    NEW_HOSTNAME="$1"
    true
  fi
  if [ $? -eq 0 ]; then
    if [ "$INIT" = "systemd" ] && systemctl -q is-active dbus && ! ischroot; then
      hostnamectl set-hostname "$NEW_HOSTNAME" 2> /dev/null
    else
      echo "$NEW_HOSTNAME" > /etc/hostname
    fi
    sed -i "s/127\.0\.1\.1.*$CURRENT_HOSTNAME/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts
    whiptail --title "Success" --msgbox "The filesystem has been expanded successfully.\n\nYou need to reboot for the changes to take effect." 20 60 1
    ASK_TO_REBOOT=1
  fi
}

do_advanced_options() {
  FUN=$(whiptail --title "Homebridge VM Configuration Tool (hb-config)" --menu "Advanced Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
    "A1 Change Hostname" "Change hostname for this computer on a network" \
    "A2 Expand Filesystem" "Expand Virtual Filesystem to current allocation" \
    3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 1 ]; then
    return 0
  elif [ $RET -eq 0 ]; then
    case "$FUN" in
      A1\ *) do_hostname ;;
      A2\ *) do_expand_filesystem ;;
      *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
    esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
  fi
}

do_configure_nginx() {
  whiptail --title "Warning" --yesno "Using this tool will overwrite any manual changes you may have made to the Homebridge Nginx config file.\n\nAre you sure you wish to continue?" 20 60 1
  RET=$?
  tempDir=$(mktemp -d)
  if [ $RET -eq 0 ]; then
    whiptail --title "Homebridge VM Configuration Tool (hb-config)" --separate-output --checklist "\nNGINX Options:"  20 80 5 --cancel-button Cancel --ok-button Save \
      "1" "Listen on port 80 - http://        " 1  \
      "2" "Listen on port 443 - https://      " 1 \
      "3" "Redirect http:// to https://       " 0 2>$tempDir/results

    if [ $? -eq 0 ]; then
       LISTEN_ON_PORT_80=false
       LISTEN_ON_PORT_443=false
       REDIRECT_HTTP_TO_HTTPS=false

       while read choice
       do
         case "$choice" in
           1) LISTEN_ON_PORT_80=true ;;
           2) LISTEN_ON_PORT_443=true ;;
           3) REDIRECT_HTTP_TO_HTTPS=true ;;
           *) ;;
         esac
       done < $tempDir/results

NGINX_PORT_80_CONFIG=""
if [ "$LISTEN_ON_PORT_80" = "true" ]; then
  NGINX_PORT_80_CONFIG="# http://\n  listen 80;                  # http IPv4\n  listen [::]:80;             # http IPv6\n"
fi

NGINX_PORT_443_CONFIG=""
if [ "$LISTEN_ON_PORT_443" = "true" ]; then
  NGINX_PORT_443_CONFIG="# https://\n  listen 443 ssl http2;       # https IPv4\n  listen [::]:443 ssl http2;  # https IPv6\n"
fi

NGINX_REDIRECT_HTTP_TO_HTTPS=""
if [ "$REDIRECT_HTTP_TO_HTTPS" = "true" ] && [ "$LISTEN_ON_PORT_80" = "true" ]; then
  NGINX_PORT_80_CONFIG=""
  NGINX_REDIRECT_HTTP_TO_HTTPS="
server {
  listen 80;                  # http IPv4
  listen [::]:80;             # http IPv6

  # replace the _ with your domain name if required
  # eg.
  # server_name example.com;
  server_name _;

  return 302 https://\$host\$request_uri;
}"
fi

NGINX_TEMPLATE="# this file was generated using the hb-config tool

server {
  $NGINX_PORT_80_CONFIG
  $NGINX_PORT_443_CONFIG
  # replace the _ with your domain name if required
  # eg.
  # server_name example.com;
  server_name _; # replace with your domain

  # path to ssl certificate file
  # If using Let's Encrypt replace this path with the location of the fullchain.pem file for your domain
  # eg.
  # ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate /etc/nginx/ssl/homebridge.local.crt;

  # path to ssl private key file
  # If using Let's Encrypt replace this path with the location of the privkey.pem file for your domain
  # eg.
  # ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
  ssl_certificate_key /etc/nginx/ssl/homebridge.local.key;

  ssl_session_cache           builtin:1000  shared:SSL:10m;
  ssl_protocols               TLSv1.2 TLSv1.3;
  ssl_ciphers                 ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers   off;
  # ssl_stapling                on;
  # ssl_stapling_verify         on;

  # large upload size to allow for uploading 3rd party backup files
  client_max_body_size 2G;

  error_page 502 /custom_502.html;

  location /startup-status.json {
    alias /usr/share/nginx/html/status.json;
  }

  location / {
    proxy_pass                  http://127.0.0.1:$(cat /etc/hb-ui-port);
    proxy_http_version          1.1;
    proxy_buffering             off;
    proxy_set_header            Host \$host;
    proxy_set_header            Upgrade \$http_upgrade;
    proxy_set_header            Connection \"Upgrade\";
    proxy_set_header            X-Real-IP \$remote_addr;
    proxy_set_header            X-Forward-For \$proxy_add_x_forwarded_for;
  }

  location = /custom_502.html {
    root /usr/share/nginx/html;
    internal;
  }
}
$NGINX_REDIRECT_HTTP_TO_HTTPS
"

      echo "$NGINX_TEMPLATE" > /etc/nginx/sites-available/homebridge.local
      /usr/local/sbin/nginx-homebridge-self-signed-cert
      systemctl enable nginx

      if systemctl is-active --quiet nginx.service; then
        echo "Restarting Nginx..."
        systemctl restart nginx
      else
        echo "Starting Nginx..."
        systemctl start nginx
      fi

      if [ $? -eq 0 ]; then
        whiptail --title "Success" --msgbox "NGINX has been configured successfully." 20 60 1
       else
        whiptail --title "Error" --msgbox "An error occured while attempting to reload the NGINX config." 20 60 1
      fi

    fi
  fi
}

do_configure_system() {
  # Use the system configuration tools available on the VM
  if command -v dpkg-reconfigure >/dev/null 2>&1; then
    dpkg-reconfigure tzdata
  else
    whiptail --title "Error" --msgbox "System configuration tool not available." 20 60 1
  fi
}

do_update() {
  tempDir=$(mktemp -d)
  scriptUrl=https://raw.githubusercontent.com/homebridge/homebridge-vm-image/latest/assets/01-homebridge/files/hb-config

  # download the update to a temporary directory
  scriptUrl=$scriptUrl?$(date --iso-8601)
  printf "Downloading hb-config update...\n$scriptUrl\n"
  curl -fL# $scriptUrl > $tempDir/hb-config

  # check the download was a success
  RET=$?
  if [ $RET -ne 0 ]; then
    whiptail --title "Error" --msgbox "An error occured while attempting to update the hb-config tool." 20 60 1
  else
    # syntax check the script is a valid bash script
    if bash -n $tempDir/hb-config; then
      chmod +x $tempDir/hb-config
      mv $tempDir/hb-config /usr/local/sbin/hb-config
      whiptail --title "Success" --msgbox "The hb-config tool has been updated and will now exit.\n\nIf you like the Homebridge VM image please show your support by starring the project on GitHub:\n\nhttps://github.com/homebridge/homebridge-vm-image" 20 60 1
      exit 0
    else
      whiptail --title "Error" --msgbox "The downloaded script was corrupted and did not pass the syntax check." 20 60 1
    fi
  fi
}

do_nmtui() {
  if systemctl is-active --quiet NetworkManager; then
    nmtui
  else
    whiptail --title "Error" --msgbox "These network options not available when WiFi was configured via VM image setup.\n\nSee the VM documentation for network configuration options." 20 60 1
  fi
}

do_about() {
  IMAGE_VERSION=$(cat /etc/hb-release)

  whiptail --title "About" --msgbox "\
This tool provides a straight-forward way of managing Homebridge on a VM. Although it can be run at any time, some of the options may have difficulties if you have heavily customised your installation.

Image Version: $IMAGE_VERSION

Homebridge - @homebridge
https://github.com/homebridge/homebridge

Homebridge Config UI X - @homebridge
https://github.com/homebridge/homebridge-config-ui-x

Homebridge VM Image - @homebridge
https://github.com/homebridge/homebridge-vm-image


\
" 20 80 1
}

# Everything else needs to be run as root
if [ $(id -u) -ne 0 ]; then
  printf "Script must be run as root. Try 'sudo hb-config'\n"
  exit 1
fi

#
# Interactive use loop
#
if [ "$INTERACTIVE" = True ]; then
  [ -e $CONFIG ] || touch $CONFIG
  calc_wt_size
  while true; do
      FUN=$(whiptail --title "Homebridge VM Image Configuration Tool (hb-config)" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
        "1 Update Node.js" "Update Node.js to the latest LTS version" \
        "2 Update Homebridge" "Update Homebridge and Node.js to the latest version using apt-pkg" \
        "3 Restore Config" "Restores the Homebridge config to the factory default" \
        "4 Nginx Options" "Configure Homebridge Nginx settings" \
        "5 Advanced Options" "Advanced Options ie expand file system, change host name" \
        "8 Update" "Update this tool to the latest version" \
        "9 About" "Information about this configuration tool" \
        3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
      do_finish
    elif [ $RET -eq 0 ]; then

        case "$FUN" in
          1\ *) do_nodejs_update ;;
          2\ *) do_homebridge_update ;;
          3\ *) do_restore_config ;;
          4\ *) do_configure_nginx ;;
          5\ *) do_advanced_options ;;
          8\ *) do_update ;;
          9\ *) do_about ;;
          *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
        esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
    else
      exit 1
    fi
  done
fi