#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\e[1m'
NC='\033[0m'

# Get system info appropriate for VM
HOSTNAME=$(hostname)
IP=$(hostname -I)
UI_PORT=$(cat /etc/hb-ui-port)
IMAGE_VERSION=$(cat /etc/hb-release)

printf "\n${RED}*** Homebridge VM Image $IMAGE_VERSION ***${NC}\n\n"

printf "homebridge was created by nfarina and licensed under the Apache License 2.0.\n" | fold -s
printf "homebridge-config-ui-x was created by oznu and licensed under the MIT License.\n\n" | fold -s

printf "To configure Homebridge browse to the one of the following addresses from another device on your network:" | fold -s
printf "\n\n"
printf "${BOLD}*${NC} ${GREEN}http://${HOSTNAME}.local:${UI_PORT}${NC}\n"

for ip in $IP; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf "${BOLD}*${NC} ${GREEN}http://$ip:${UI_PORT}${NC}\n"
  else
    printf "${BOLD}*${NC} ${GREEN}http://[$ip]:${UI_PORT}${NC}\n"
  fi
done

printf "\nAll Homebridge configuration can be completed via the Homebridge Web UI.\n" | fold -s

printf "\n${BOLD}Homebridge storage path:${NC} ${GREEN}/var/lib/homebridge${NC}\n"
printf "${BOLD}Homebridge config.json path:${NC} ${GREEN}/var/lib/homebridge/config.json${NC}\n"

printf "\n${BOLD}Restart Homebridge CMD:${NC} ${GREEN}sudo hb-service restart${NC}\n"
printf "${BOLD}View Logs CMD:${NC} ${GREEN}sudo hb-service logs${NC}\n"

printf "\n${BOLD}Manage Server:${NC} ${GREEN}sudo hb-config${NC}\n"
printf "${BOLD}Enter Homebridge Runtime Environment:${NC} ${GREEN}sudo hb-shell${NC}\n"

# Display SSH access information (password shown only once during first boot)
if [ -f /etc/hb-root-password-set ]; then
  printf "\n${BOLD}SSH Access:${NC} ${GREEN}ssh root@${HOSTNAME}.local${NC} or ${GREEN}ssh root@$(echo $IP | awk '{print $1}')${NC}\n"
  printf "${BOLD}Note:${NC} Root password was shown once during first boot. Use 'passwd' to change it.\n"
else
  printf "\n${BOLD}SSH Access:${NC} Root password will be generated on first boot.\n"
fi

printf "\n"
