name: Release Stage 3 - Package Release 
run-name: Release Stage 3 - Package Release - Run ${{ inputs.run_id }}

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Run ID of the build workflow that produced the artifacts'
        required: true
        type: string
      release_stream:
        description: 'Release stream (stable, beta, alpha)'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: beta
      HOMEBRIDGE_VM_IMAGE_VERSION:
        description: 'Homebridge VM image version aka release tag'
        required: true
        type: string

env:
  VDISK_SIZE: 50G  # Size of the virtual disk for each VM

concurrency:
  group: package-and-validate-virtualbox
  cancel-in-progress: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        pattern: homebridge-image-*
        path: ./output
        run-id: ${{ inputs.run_id }}
        merge-multiple: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: List Downloaded Artifacts
      run: ls -lR ./output

    - name: Install QEMU
      run: |
        echo "::group::Installing QEMU"
        sudo apt-get update
        sudo apt-get install -y qemu-utils
        echo "::endgroup::"

    - name: Set Release Title
      id: set_title
      run: |
        if [[ "${{ inputs.release_stream }}" == "beta" ]]; then
          echo "RELEASE_TITLE=BETA: Homebridge VM Image Release ${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.release_stream }}" == "alpha" ]]; then
          echo "RELEASE_TITLE=ALPHA: Homebridge VM Image Release ${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" >> $GITHUB_OUTPUT
        else
          echo "RELEASE_TITLE=Homebridge VM Image Release ${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release Body
      id: release_body
      run: |
        ./scripts/create-release-body.sh "${{ inputs.release_stream }}"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create GitHub Prerelease
      id: create_release
      uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}
        prerelease: true
        draft: false
        name: ${{ steps.set_title.outputs.release_title }}
        files: |
          ./output/*.manifest
        body: Placeholder, will be updated in next step
        if-no-files: true
        clear_attachments: true
        fail_on_no_files: false

    - name: Update release body
      uses: tubone24/update_release@v1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}
      with:
        body_path: ./output/release-body.md

    - name: Convert, Compress, and Upload Each Disk Format
      run: |
        set -e
        RELEASE_ID=$(gh release view "${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" --json id -q .id)
        for img in ./output/*.img; do
          base_name=$(basename "$img" .img)
          # Convert to qcow2 format
          ext=qcow2
          out_file="./output/${base_name}.${ext}"
          qemu-img convert -c -O $ext "$img" "$out_file"
          qemu-img resize "$out_file" ${VDISK_SIZE}
          echo "Uploading $out_file to release"
          gh release upload "${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" "$out_file" --clobber
          rm -f "$out_file"
          # Remaining files don't have the -c option for qemu-img
          for ext in vdi vhdx vmdk; do
            out_file="./output/${base_name}.${ext}"
            gz_file="${out_file}.gz"
            echo "Converting $img to $ext format"
            qemu-img convert -O $ext "$img" "$out_file"
            qemu-img resize "$out_file" ${VDISK_SIZE} || true
            echo "Compressing $out_file"
            gzip -k "$out_file"
            echo "Uploading $gz_file to release"
            gh release upload "${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}" "$gz_file" --clobber
            echo "Deleting $out_file and $gz_file to save space"
            rm -f "$out_file" "$gz_file"
          done
        done
        echo "Deleting original IMG files"
        rm -f ./output/*.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release created
      run: |
        echo "::notice::Release ${{ steps.set_title.outputs.RELEASE_TITLE }} created successfully."

  invoke-appliance-packaging:
    needs: [create-release]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        packaging_workflow: [package-for-utm.yml, package-for-virtualbox.yml]
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v5

    # Step 2: Trigger Packaging and Validation Workflow
    - name: Trigger Packaging and Validation Workflow
      run: |
        gh workflow run "${{ matrix.packaging_workflow }}" \
          --ref "latest" \
          --field release_stream="${{ inputs.release_stream }}" \
          --field run_id="${{ inputs.run_id }}" \
          --field HOMEBRIDGE_VM_IMAGE_VERSION="${{ inputs.HOMEBRIDGE_VM_IMAGE_VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}