name: Release Stage 2 - Build and Push Homebridge VM Images
run-name: Release Stage 2 - ${{ github.event.inputs.Scheduled}} - Build and Push - ${{ inputs.release_stream }} - ${{ github.run_id }}

on:
  workflow_dispatch:
    inputs:
      release_stream:
        description: 'Choose release type: "stable" (builds latest version), "beta" (builds beta version with beta-YYYY-MM-DD tag), or "alpha" (builds alpha version with alpha-YYYY-MM-DD tag).'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
        default: beta
      Scheduled:
          description: 'Whether this is a scheduled run'
          required: false
          type: choice
          options:
            - Scheduled
            - Manual
          default: Manual

concurrency:
  group: stage-2-build-and-push
  cancel-in-progress: false

jobs:
  set-versions:
    runs-on: ubuntu-latest
    outputs:
      HOMEBRIDGE_VM_IMAGE_VERSION: ${{ steps.docker_version.outputs.HOMEBRIDGE_VM_IMAGE_VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Docker Homebridge version
      id: docker_version
      run: |
        if [[ "${{ inputs.release_stream }}" == "stable" ]]; then
          export HOMEBRIDGE_VM_IMAGE_VERSION="$(date +%Y-%m-%d)"
        else
          export HOMEBRIDGE_VM_IMAGE_VERSION="${{ inputs.release_stream }}-$(date +%Y-%m-%d)"
        fi
        echo "HOMEBRIDGE_VM_IMAGE_VERSION=${HOMEBRIDGE_VM_IMAGE_VERSION}" >> $GITHUB_OUTPUT

    - name: Output versions
      run: |
        echo "::group::Version Information"
        echo "HOMEBRIDGE_VM_IMAGE_VERSION=${{ steps.docker_version.outputs.HOMEBRIDGE_VM_IMAGE_VERSION }}"
        echo "::endgroup::"

  build-img-file:
    needs: set-versions
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        arch: [arm64, amd64]
        include:
          - arch: arm64
            runs-on: ubuntu-24.04-arm
          - arch: amd64
            runs-on: ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup build environemnt
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap parted e2fsprogs dosfstools dialog qemu-user-static gzip sudo udev kpartx psmisc jq zerofree        
          sudo apt-get install -y grub-efi-${{ matrix.arch }}-bin

      # Step 2: Start the build process
      - name: run build-debian-image.sh script
        run: |
          ./build-debian-image.sh "${{ matrix.arch}}" "${{ inputs.release_stream }}" "${{ needs.set-versions.outputs.HOMEBRIDGE_VM_IMAGE_VERSION }}"

      # Step 3: Upload the IMG file as an artifact
      - name: Upload Homebridge Image
        uses: actions/upload-artifact@v4
        with:
          retention-days: 7
          name: homebridge-image-${{ matrix.arch }}
          path: output/*

      - name: Steps complete
        run: |
          echo "::notice::Homebridge VM image version: ${{ needs.set-versions.outputs.HOMEBRIDGE_VM_IMAGE_VERSION }}"
          echo "::notice::Run ID: ${{ github.run_id }}"
          echo "::notice::Architecture: ${{ matrix.arch }}"
          echo "::notice::Release Stream: ${{ inputs.release_stream }}"

  invoke-package-and-validate:
    needs: [set-versions, build-img-file]
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v5

    # Step 2: Trigger Packaging and Validation Workflow
    - name: Trigger Release Packaging Workflow
      run: |
        gh workflow run "release-stage-3_package_release.yml" \
          --ref "latest" \
          --field release_stream="${{ inputs.release_stream }}" \
          --field run_id="${{ github.run_id }}" \
          --field HOMEBRIDGE_VM_IMAGE_VERSION="${{ needs.set-versions.outputs.HOMEBRIDGE_VM_IMAGE_VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
